version: '3'

services:
  sly-mysql:
    image: sly-mysql
    build:
      context: ./resources/mysql/
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 2s
      retries: 10
  
  sly-api:
    image: sly-api
    build: .
    #depends_on:
    #  sly-mysql:
    #    condition: service_healthy
    ports:
      - 8080:8080
    links:
      - sly-mysql
